### PR TITLE
fixed  some text and background color

### PR DESCRIPTION
**Pull request by nathanhartman77**
I thought there would be more.  It was just driving me a little crazy.

### CODE REVIEW

**Review by davidmitrano — CHANGES_REQUESTED** [review]
I believe we are merging into dev. not master.

**Review by eelia001 — CHANGES_REQUESTED** [review]
As david said

**Review by eelia001 — APPROVED** [review]
Fixed the issue, if it happens again just go to edit to the right of the pull request title and change it. When making a pull request, make sure you select dev as the base branch.

**Review by davidmitrano — APPROVED** [review]
Approved.

**Pull request merged**
